config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'product_resistration' => 'products#new'
  resources :users, only: [:show, :create]
  resources :products, only: [:show, :create]
  resources :bids, only: [:create]
end

app/models/bid.rb
class Bid < ActiveRecord::Base
  validates :user_id, presence: true
  validates :product_id, presence: true
  validates :current_bid, presence: true, length: { maximum: 8 }
  belongs_to :user
  belongs_to :product

  def greater_price?
    current_bid > product.current_bid
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  has_many :bids
  validates :user_id, presence: true
  validates :name, presence: true, length: { maximum: 64 }
  validates :current_bid, presence: true, length: { maximum: 8 }
  validates :discription, presence: true, length: { maximum: 128 }
  validates :time_left, presence: true

  def update_price(bidding_price)
    self.current_bid = bidding_price
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, length: {maximum: 32}
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}
  has_many :products
  has_many :bids

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ?
      BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def product_item
    Product.where.not(id: nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  include ProductsHelper
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController

  def create
    @bid = current_user.bids.build(bid_params)
    @product = Product.find(@bid.product_id)

    if product_myself?
      render_error_messages("自分の商品に入札はできません。")
    elsif @bid.current_bid.blank?
      render_error_messages("入札内容が適切ではありません")
    elsif !@bid.greater_price?
      render_error_messages("入札金額が低いため入札できませんでした。")
    else

      Bid.transaction do
        @bid.save!
        @product.update_price(@bid.current_bid)
        @product.save!
      end
      flash[:success] = "入札に成功しました。"
      redirect_to product_path(@bid.product_id)
    end
    rescue ActiveRecord::RecordInvalid
      render_error_messages("入力された金額が大きすぎます。")
   end

  private

  def bid_params
    params.require(:bid).permit(:product_id, :current_bid)
  end

  def render_error_messages(message)
    flash.now[:danger] = message
    render 'products/show'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if logged_in?
      @product_list = current_user.product_item.paginate(page: params[:page])
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def show
    @product = Product.find(params[:id])
    @bid = Bid.new(product_id: @product.id)
  end

  def new
    @product = Product.new
  end

  def create
    @product = current_user.products.build(product_params)
    if @product.save
      flash[:success] = "商品が登録されました！"
      redirect_to @product
    else
      render 'new'
    end
  end

  private

  def product_params
    params.require(:product).permit(:name,
                                    :current_bid,
                                    :discription,
                                    :time_left)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by(name: params[:session][:name])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'ユーザーネーム、又はパスワードが正しくありません。'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @products = @user.products.paginate(page: params[:page])
    @bid_items = my_bid_list
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end

  def my_bid_list
    bid_ids = Bid.where("user_id = ?", @user).
      select(:product_id).
      uniq
    return Product.where(id: bid_ids.pluck(:product_id))
  end
end

app/helpers/products_helper.rb
module ProductsHelper

  def product_myself?
    current_user.id == @product.user_id
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/views/home/index.html.erb
<h1>Home Page</h1>
<p>レイアウトを少し頑張りました。</p>

<% if logged_in? %>
  <div class="col-md-8">
    <h3>出品商品一覧</h3>
    <% if @product_list.any? %>
      <ol class="products">
        <%= render @product_list %>
      </ol>
      <%= will_paginate @product_list %>
    <% end %>
  </div>
<% else %>
  <%= link_to "サインアップ!", signup_path %>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "TSO", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "ホーム", root_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%=link_to "マイページ", current_user %></li>
              <li class="divider"></li>
              <li>
                <%=link_to "ログアウト", logout_path, method:"delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_product.html.erb
<li id="product-<%= product.id %>">
  <span class="name">商品名　 : <%= link_to product.name, product %></span>
  <br />
  <span class="user">出品者名 : <%= link_to product.user.name, product.user %></span>
  <br />
  <span class="current_bid">現在価格 : <%= product.current_bid %> 円</span>
  <br />
  <span class="time_left">取引期限 : <%= product.time_left %></span>
</li>

app/views/products/new.html.erb
<h1>Product Resistration</h1>
<p>登録する商品の情報を入力してください。</p>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@product) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name, "名前" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :current_bid, "価格" %>
      <%= f.text_field :current_bid, class: 'form-control' %>

      <%= f.label :time_left, "取引期間" %>
      <%= f.datetime_field :time_left, class: 'form-control' %>

      <%= f.label :discription, "備考欄" %>
      <%= f.text_area:discription, class: 'form-control' %>

      <%= f.submit "登録する！", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<p>商品詳細</p>

<div>
  <ol>
    <li>現在値 : <%= @product.current_bid %> 円</li>
    <li>取引期限 : <%= @product.time_left %></li>
    <li>備考欄 : <%= @product.discription %></li>
  </ol>
  <% if product_myself? %>
  <% else %>
    <%= form_for (@bid) do |f| %>

      <%= f.hidden_field :product_id %>

      <%= f.label :current_bid, "入札額" %>
      <%= f.text_field :current_bid, class: 'form-control' %>

      <%= f.submit "入札する！", class: "btn btn-primary" %>
    <% end %>
  <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<p>ユーザー情報を入力してください。</p>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name, "名前" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "もう一度入力" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "登録する！", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>マイページ</h1>
<div class="col-md-8">
  <%= @user.name %> さんの個人ページ
  <div class="row">
    <aside class="col-md-4">
      <%= link_to "商品の登録", product_resistration_path %>
    </aside>
  </div>
  <% if @user.products.any? %>
    <h3>登録商品(<%= @user.products.count %>)</h3>
    <ol class="porducts">
      <%= render @products %>
    </ol>
    <%= will_paginate @products %>
  <% end %>

  <% if @user.bids.any? %>
    <h3>入札商品(<%= @bid_items.count %>)</h3>
    <ol class="bids">
      <%= render @bid_items %>
    </ol>
    <%= will_paginate @products %>
  <% end %>

</div>